print("Hello World!")
print("Hello Again")
print("I like typing this")
print("This is fun!")
print('Yay! Printing!')
print("I'd Much rather you 'not'.")
print('I "said" do not touch this.')
print("This is another line!")
# print('This is a commented out line')
print("You didn't even see the line above me. lol, lame")
